// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TriviaBackend.Data;

#nullable disable

namespace TriviaBackend.Migrations
{
    [DbContext(typeof(TriviaDbContext))]
    partial class TriviaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TriviaBackend.Models.Objects.TriviaQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Category = 3,
                            CorrectAnswerIndex = 1,
                            Difficulty = 1,
                            Options = "[\"Paris\",\"Tokyo\",\"Shanghai\",\"Gelgaudi\\u0161kis\"]",
                            QuestionText = "What is the most populated city?",
                            TimeLimit = 20
                        },
                        new
                        {
                            Id = 200,
                            Category = 3,
                            CorrectAnswerIndex = 3,
                            Difficulty = 2,
                            Options = "[\"pi\",\"e\",\"golden ratio\",\"square root of 2\"]",
                            QuestionText = "which is least",
                            TimeLimit = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
